[project]
name = "pubtrends"
version = "1.0.0"
description = "Interactive scientific literature exploration tool"
requires-python = "==3.10.*"
dependencies = [
    "biopython==1.79",
    "bokeh==3.6.3",
    "cachetools==5.5.2",
    "celery==5.4.0",
    "fastparquet==2024.2.0",
    "flask==3.1.0",
    "flask-admin==1.6.0",
    "flask-caching==2.3.1",
    "flask-security==5.6.0",
    "flask-sqlalchemy==3.1.1",
    "jinja2==3.1.6",
    "ipywidgets==8.1.5",
    "holoviews==1.20.1",
    "huggingface-hub==0.29.1",
    "gensim==4.3.3",
    "matplotlib==3.10.1",
    "more-itertools==10.6.0",
    "networkx==3.4.2",
    "nltk==3.9.1",
    "pandas==2.2.3",
    "parameterized==0.9.0",
    "psutil==7.0.0",
    "psycopg2-binary==2.9.9",
    "pyarrow==21.0.0",
    "pytest==8.3.5",
    "requests==2.32.3",
    "scikit-learn==1.6.1",
    "scipy==1.13.1",
    "seaborn==0.13.2",
    "spacy==3.8.2",
    "statsmodels==0.14.4",
    "sqlalchemy==2.0.38",
    "tqdm==4.67.1",
    "umap-learn==0.5.7",
    "unidecode==1.3.8",
    "wordcloud==1.9.4",
    "email-validator==2.2.0",
    "gunicorn==23.0.0",
    "redis==5.2.1",
    "lazy==1.6",
    "pytest-flake8==1.3.0",
    "python-levenshtein==0.27.1",
    "shapely==2.1.2",
    "teamcity-messages==1.33",
    "text2num==2.5.1",
    "vine==5.1.0",
    "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
