version: "3"
services:
  web:
    build:
      context: ..
      dockerfile: pysrc/app/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
      embeddings:
        condition: service_healthy
      celery:
        condition: service_started
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/nltk_data:/home/user/nltk_data
      - ~/.pubtrends/database:/database
      - ~/.pubtrends/results:/results

  celery:
    build:
      context: ..
      dockerfile: pysrc/celery/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      embeddings:
        condition: service_healthy
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/results:/results
      - ~/.pubtrends/nltk_data:/home/user/nltk_data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data

  redis:
    image: redis:7.4.2
    volumes:
      - ~/.pubtrends/logs:/log
    # This command is used to process huge analysis results of 40k+ papers
    command: redis-server --timeout 0 --client-output-buffer-limit normal 0 0 0
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  embeddings:
    build:
      context: ..
      dockerfile: pysrc/endpoints/embeddings/fasttext/Dockerfile
    restart: always
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/fasttext:/fasttext
      - ~/.pubtrends/nltk_data:/home/user/nltk_data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data
    healthcheck:
      test: [ "CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5001')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
